<a href="https://colab.research.google.com/github/mjavadpur/KNN/blob/main/HeartDisease_Session4_Mjavadpur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [64]:
import pandas as pd
import numpy as np
import sklearn.preprocessing as prp
import warnings
warnings.filterwarnings('ignore')

In [65]:
df = pd.read_csv('/content/drive/MyDrive/Workshop/KNN/heart.csv')


In [66]:
df

age  sex  cp  trtbps  chol  fbs  restecg  thalachh  exng  oldpeak  slp  \
0     63    1   3     145   233    1        0       150     0      2.3    0   
1     37    1   2     130   250    0        1       187     0      3.5    0   
2     41    0   1     130   204    0        0       172     0      1.4    2   
3     56    1   1     120   236    0        1       178     0      0.8    2   
4     57    0   0     120   354    0        1       163     1      0.6    2   
..   ...  ...  ..     ...   ...  ...      ...       ...   ...      ...  ...   
298   57    0   0     140   241    0        1       123     1      0.2    1   
299   45    1   3     110   264    0        1       132     0      1.2    1   
300   68    1   0     144   193    1        1       141     0      3.4    1   
301   57    1   0     130   131    0        1       115     1      1.2    1   
302   57    0   1     130   236    0        0       174     0      0.0    1   

     caa  thall  output  
0      0      1       1  
1      0      2       1  
2      0      2       1  
3      0      2       1  
4      0      2       1  
..   ...    ...     ...  
298    0      3       0  
299    0      3       0  
300    2      3       0  
301    1      3       0  
302    1      2       0  

[303 rows x 14 columns]

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trtbps    303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalachh  303 non-null    int64  
 8   exng      303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64  
 11  caa       303 non-null    int64  
 12  thall     303 non-null    int64  
 13  output    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [68]:
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [69]:
df.mean()

age          54.366337
sex           0.683168
cp            0.966997
trtbps      131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalachh    149.646865
exng          0.326733
oldpeak       1.039604
slp           1.399340
caa           0.729373
thall         2.313531
output        0.544554
dtype: float64

In [70]:
df.std()

age          9.082101
sex          0.466011
cp           1.032052
trtbps      17.538143
chol        51.830751
fbs          0.356198
restecg      0.525860
thalachh    22.905161
exng         0.469794
oldpeak      1.161075
slp          0.616226
caa          1.022606
thall        0.612277
output       0.498835
dtype: float64

In [71]:
df.columns

Index(['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall', 'output'],
      dtype='object')

In [72]:
X = df[['age', 'sex', 'cp', 'trtbps', 'chol', 'fbs', 'restecg', 'thalachh',
       'exng', 'oldpeak', 'slp', 'caa', 'thall']].values

X

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [73]:
y = df['output'].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [74]:
scalar = prp.StandardScaler().fit(X)
X= scalar.transform(X.astype(float))

X

array([[ 0.9521966 ,  0.68100522,  1.97312292, ..., -2.27457861,
        -0.71442887, -2.14887271],
       [-1.91531289,  0.68100522,  1.00257707, ..., -2.27457861,
        -0.71442887, -0.51292188],
       [-1.47415758, -1.46841752,  0.03203122, ...,  0.97635214,
        -0.71442887, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.93851463, ..., -0.64911323,
         1.24459328,  1.12302895],
       [ 0.29046364,  0.68100522, -0.93851463, ..., -0.64911323,
         0.26508221,  1.12302895],
       [ 0.29046364, -1.46841752,  0.03203122, ..., -0.64911323,
         0.26508221, -0.51292188]])

In [75]:
print(X.mean())
print(X.std())

-1.407015318336832e-16
0.9999999999999999


In [76]:
def ensmble_k(X, y):
  from sklearn.model_selection import train_test_split
  from sklearn.neighbors import KNeighborsClassifier
  from sklearn import neighbors
  from sklearn import metrics
  HParams = pd.DataFrame({'k':[], 'Train Accuracy':[], 'Test Accuracy':[],'Overfit':[]}) 
  for k in range(1,100):
      X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2 , shuffle = True, random_state = 4)

      neighb = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train)

      y_pred_train = neighb.predict(X_train)
      acc_train = metrics.accuracy_score(y_train, y_pred_train)

      yhat = neighb.predict(X_test)
      acc_test = metrics.accuracy_score(y_test, yhat)

      Overfit = abs(acc_train - acc_test)

      new_hp = pd.DataFrame({"k":[k],"Train Accuracy":[acc_train],"Test Accuracy":[acc_test] ,"Overfit":[Overfit]})

      HParams = HParams.append(new_hp)

  return HParams



      


In [77]:
hyperParams = ensmble_k(X,y)


In [80]:
hyperParams = hyperParams.loc[hyperParams['Overfit']<0.05]


result = hyperParams['Train Accuracy'].values
best_HP = hyperParams.iloc[result.argmax(),:]

train_acc = best_HP['Train Accuracy']
test_acc = best_HP['Test Accuracy']
k = best_HP['k']

print('Best Train Accuracy:{} in k: {} , Test Accuracy:{} '.format(train_acc, k, test_acc))


result = hyperParams['Test Accuracy'].values
best_HP = hyperParams.iloc[result.argmax(),:]

train_acc = best_HP['Train Accuracy']
test_acc = best_HP['Test Accuracy']
k = best_HP['k']

print('Best Test Accuracy:{} in k: {} , Train Accuracy:{} '.format(test_acc, k, train_acc))

Best Train Accuracy:0.8636363636363636 in k: 8.0 , Test Accuracy:0.819672131147541 
Best Test Accuracy:0.8688524590163934 in k: 22.0 , Train Accuracy:0.8264462809917356 


In [79]:
hyperParams

k  Train Accuracy  Test Accuracy   Overfit
0   6.0        0.859504       0.819672  0.039832
0   7.0        0.851240       0.836066  0.015174
0   8.0        0.863636       0.819672  0.043964
0   9.0        0.847107       0.819672  0.027435
0  10.0        0.838843       0.852459  0.013616
0  11.0        0.834711       0.819672  0.015039
0  12.0        0.847107       0.836066  0.011042
0  13.0        0.847107       0.819672  0.027435
0  14.0        0.842975       0.836066  0.006910
0  15.0        0.830579       0.803279  0.027300
0  16.0        0.834711       0.819672  0.015039
0  17.0        0.826446       0.803279  0.023168
0  18.0        0.830579       0.803279  0.027300
0  19.0        0.822314       0.836066  0.013752
0  20.0        0.830579       0.852459  0.021881
0  22.0        0.826446       0.868852  0.042406
0  23.0        0.822314       0.852459  0.030145
0  24.0        0.830579       0.836066  0.005487
0  26.0        0.830579       0.836066  0.005487
0  27.0        0.818182       0.852459  0.034277
0  28.0        0.822314       0.836066  0.013752
0  30.0        0.818182       0.836066  0.017884
0  31.0        0.822314       0.852459  0.030145
0  32.0        0.818182       0.836066  0.017884
0  33.0        0.822314       0.868852  0.046538
0  34.0        0.826446       0.852459  0.026013
0  35.0        0.818182       0.852459  0.034277
0  36.0        0.822314       0.868852  0.046538
0  40.0        0.822314       0.868852  0.046538
0  42.0        0.822314       0.868852  0.046538
0  43.0        0.818182       0.852459  0.034277
0  44.0        0.822314       0.852459  0.030145
0  45.0        0.822314       0.852459  0.030145
0  46.0        0.822314       0.852459  0.030145
0  47.0        0.818182       0.852459  0.034277
0  48.0        0.818182       0.852459  0.034277